export default async function Head({params}: {params: {pokemon: string}}) {
  let name: string = params.pokemon;
  return (
    <>
      <title>{name.charAt(0).toUpperCase() + name.slice(1)}</title>
      <meta content='width=device-width, initial-scale=1' name='viewport' />
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
    </>
  );
}
