import Head from 'next/head';
import { SetStateAction, useState } from 'react';
import { Inter } from '@next/font/google';
const inter = Inter({ subsets: ['latin'] });
import { Container, Grid, Textarea, Link, Input } from '@nextui-org/react';
import PokeCard from '@/components/PokeCard';
import allPokemon from '@/api/pokemon';

export default function Home() {
  const [pokimens, setPokimens] = useState([...allPokemon.pokemon]);
  const [filter, setFilter] = useState('');
  const [maxItems, setMaxItems] =  useState(50);
  allPokemon.onChange = () => {
    setPokimens([...allPokemon.pokemon]);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Container
        responsive
        display='flex'
        justify='center'
        alignContent='center'
      >
        <Input
          label='Search for a pokemon'
          placeholder='Ditto'
          underlined
          type='text'
          css={{
            mb: '$10',
            mr: '$10',
          }}
          onChange={(e) => setFilter(e.target.value)}
        />
        <Input
          clearable
          underlined
          label='Max items'
          helperText='0 for infinite scroll'
          type='number'
          initialValue='50'
          placeholder='50'
          css={{
            mb: '$10',
          }}
          onChange={(e) => setMaxItems(Number(e.target.value))}
        />

        <Grid.Container gap={2} justify='center' className={inter.className}>
          {pokimens
            .filter((pokemon) => pokemon.name.includes(filter.toLowerCase()))
            .slice(0, maxItems || Infinity)
            .map((pokemon) => {
              return (
                <Grid key={pokemon.id}>
                  <PokeCard
                    name={pokemon.name}
                    image={pokemon.sprites.front_default}
                    types={pokemon.types}
                    id={pokemon.id}
                    key={pokemon.name}
                  />
                </Grid>
              );
            })}
        </Grid.Container>
        <Container
          fluid
          justify='center'
          alignContent='center'
          css={{ display: 'flex', textAlign: 'center', m: 2, p: 2 }}
        >
          <Link href='https://pokeapi.co/'>API by PokeApi</Link>
        </Container>
      </Container>
    </>
  );
}
