import Head from 'next/head';
import { useState } from 'react';
import { Inter } from '@next/font/google';
const inter = Inter({ subsets: ['latin'] });
import { Container, Grid, Textarea, Link, Spacer } from '@nextui-org/react';
import PokeCard from '../components/PokeCard';
import allPokemon from '../api/pokemon';

export default function Home() {
  const [pokimens, setPokimens] = useState([...allPokemon.pokemon]);
  const [filter, setFilter] = useState('');
  allPokemon.onChange = () => {
    setPokimens([...allPokemon.pokemon]);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Container
        responsive
        display='flex'
        justify='center'
        alignContent='center'
      >
        <Textarea
          label='Search for a pokemon'
          placeholder='Ditto'
          underlined
          minRows={1}
          maxRows={3}
          css={{
            mb: '$10',
            minWidth: '25%',
          }}
          onChange={(e) => setFilter(e.target.value)}
        ></Textarea>
        <Grid.Container gap={2} justify='center' className={inter.className}>
          {pokimens
            .filter((pokemon) => pokemon.name.includes(filter.toLowerCase()))
            .map((pokemon) => {
              return (
                <Grid key={pokemon?.data?.id}>
                  <PokeCard
                    name={pokemon.name}
                    image={pokemon.data.sprites.front_default}
                    types={pokemon.data.types}
                    key={pokemon.name}
                  />
                </Grid>
              );
            })}
        </Grid.Container>
        <Container
          fluid
          justify='center'
          alignContent='center'
          css={{ display: 'flex', textAlign: 'center', m: 2, p: 2 }}
        >
          <Link href='https://pokeapi.co/'>API by PokeApi</Link>
        </Container>
      </Container>
    </>
  );
}
